export const lightTheme = {
  primary: "#353699",
  secondry: "#fff",
  mainHeadingColor: "#BF616A",
  mainHeadingBackgroundColor: "#ECEFF4",
  subHeadingColor: "#D08770",
  layoutContainerColor: "#ECEFF4",
  toggleButtonWrapperColor: "#ECEFF4",
  tagNameColor: "#EBCB8B",
  tagLineColor: "#A3BE8C",
  tagLineBackgroundColor: "#ECEFF4",
  cheatCardHeadingColor: "#D08770",
  codeWrapperBackgroundColor: "#ECEFF4",
  codeWrapperBorder: "1.5px solid #BF616A",
  iconColor: "#D08770",
  iconHoverColor: "#ECEFF4",
  iconHoverBackgroundColor: "#BF616A",
  iconBorderRadius: "0px 0px 0px 5px",
  iconTransition: "0.5s",
  themeType: "light",
  codeBlockBackgroundColor: "#4C566A",
  codeBlockBackgroundHoverColor: "#434C5E",
  // text: '#363537',
  // toggleBorder: '#FFF',
  // gradient: 'linear-gradient(#39598A, #79D7ED)',
}

export const darkTheme = {
  backgroundColor: "#2E3440",
  textColor: "#D8DEE9",
  linkColor: "#A3BE8C",
  dividerColor: "#4C566A",
  codeBlockBackgroundColor: "#3B4252",
  codeBlockBackgroundHoverColor: "#434C5E",
}
